package cn.oyzh.easyredis.terminal;

import cn.oyzh.easyredis.terminal.acl.RedisAclCatTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclDeluserTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclDryrunTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclGenpassTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclGetuserTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclListTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclLoadTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclLogTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclSaveTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclSetuserTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclUsersTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.acl.RedisAclWhoamiTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisAuthTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisConnectTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisDelTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisDumpTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisEchoTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisExistsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisFlushallTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisFlushdbTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisGetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisGetdelTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisHelloTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisKeysTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisMigrateTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisMoveTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisPingTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisRandomkeyTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisRenameTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisRenamenxTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisRestoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisSelectTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisSetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisSwapdbTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisTypeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.base.RedisUnlinkTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.bit.RedisBitcountTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.bit.RedisBitfieldTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.bit.RedisBitfield_r0TerminalCommandHandler;
import cn.oyzh.easyredis.terminal.bit.RedisBitposTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.bit.RedisBittopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.bit.RedisGetbitTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.bit.RedisSetbitTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.bit.RedisSetrangeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientCachingTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientGetnameTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientGetredirTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientIdTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientInfoTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientKillTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientListTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientNoevictTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientNotouchTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientPuaseTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientReplyTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientSetinfoTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientSetnameTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientTrackingTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientTrackinginfoTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientUnblockTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.client.RedisClientUnpuaseTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterAddSlotsRangeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterAddSlotsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterBumpEpochTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterCountFailureReportsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterCountKeysInSlotTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterDelSlotsRangeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterDelSlotsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterFailoverTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterFlushSlotsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterForgetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterGetKeysInSlotTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterInfoTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterKeyslotTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterLinksTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterMeetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterMyShardIdTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterMyidTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterNodesTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterReplicateTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterResetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterSaveConfigTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterSetConfigEpochTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterSetSlotTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterShardsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterSlavesTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterSlotsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.cluster.RedisClusterTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.command.RedisCommandCountTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.command.RedisCommandDocsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.command.RedisCommandGetkeysTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.command.RedisCommandGetkeysandflagsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.command.RedisCommandInfoTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.command.RedisCommandListTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.command.RedisCommandTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeoaddTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeodistTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeohashTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeoposTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeoradiusTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeoradius_r0TerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeoradiusbymemberTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeoradiusbymember_r0TerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeosearchTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.geo.RedisGeosearchstoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHdelCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHexistsCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHgetCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHgetallCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHincrbyTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHincrbyfloatTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHkeysCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHlenCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHmgetCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHrandfieldCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHscanTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHsetCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHsetnxCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHstrlenCommandHandler;
import cn.oyzh.easyredis.terminal.hash.RedisHvalsCommandHandler;
import cn.oyzh.easyredis.terminal.hylog.RedisPfaddTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.hylog.RedisPfcountTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.hylog.RedisPfmergeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisCopyTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisDbSizeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisExpireTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisExpireatTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisExpiretimeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisGetexTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisPersistTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisPexpireTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisPexpireatTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisPexpiretimeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisPttlTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisScanTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.key.RedisTtlTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.latency.RedisLatencyDoctorTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.latency.RedisLatencyGraphTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.latency.RedisLatencyHistogramTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.latency.RedisLatencyHistoryTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.latency.RedisLatencyLatestTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.latency.RedisLatencyResetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.latency.RedisLatencyTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisBlmoveTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisBlmpopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisBlpopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisBrpopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisBrpoplpushTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLindexTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLinsertTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLlenTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLmoveTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLmpopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLpopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLposTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLpushTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLpushxTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLrangeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLremTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLsetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisLtrimTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisRpopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisRpoplpushTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisRpushTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.list.RedisRpushxTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.memory.RedisMemoryDoctorTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.memory.RedisMemoryMallocstatsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.memory.RedisMemoryPurgeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.memory.RedisMemoryStatsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.memory.RedisMemoryTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.memory.RedisMemoryUsageTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.module.RedisModuleListTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.module.RedisModuleLoadTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.module.RedisModuleLoadexTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.module.RedisModuleTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.module.RedisModuleUnloadTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisAskingTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisBgrewriteaofTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisBgsaveTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisFailoverTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisLastsaveTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisLolwutTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisObjectTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisReadonlyTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisReadwriteTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisReplicaofTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisResetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisRoleTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisSaveTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisSlaveofTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisTimeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisTouchTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisWaitTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.other.RedisWaitaofTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.RedisEvalTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.RedisEval_r0TerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.RedisEvalshaTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.RedisEvalsha_r0TerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.RedisFcallTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.RedisFcall_r0TerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.function.RedisFunctionDeleteTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.function.RedisFunctionDumpTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.function.RedisFunctionFlushTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.function.RedisFunctionKillTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.function.RedisFunctionListTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.function.RedisFunctionLoadTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.function.RedisFunctionRestoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.function.RedisFunctionStatsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.function.RedisFunctionTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.script.RedisScriptDebugTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.script.RedisScriptExistsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.script.RedisScriptFlushTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.script.RedisScriptKillTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.script.RedisScriptLoadTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.program.script.RedisScriptTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.pubsub.RedisPsubscribeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.pubsub.RedisPublishTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.pubsub.RedisPubsubTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.pubsub.RedisPunsubscribeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.pubsub.RedisSpublishTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.pubsub.RedisSsubscribeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.pubsub.RedisSubscribeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.pubsub.RedisSunsubscribeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.pubsub.RedisUnsubscribeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisDiscardTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisExecTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisInfoTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisLcsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisMonitorTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisMuiltTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisShutdownTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisSortTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisSort_r0TerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisUnwatchTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.RedisWatchTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.config.RedisConfigGetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.config.RedisConfigResetStatTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.config.RedisConfigRewriteTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.config.RedisConfigSetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.server.config.RedisConfigTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSaddTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisScardTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSdiffTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSdiffstoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSinterTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSintercarkTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSinterstoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSismemberCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSmembersCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSmismemberCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSmoveTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSpopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSrandmemberCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSremCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSscanTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSunionTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.set.RedisSunionstoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.slowlog.RedisSlowlogGetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.slowlog.RedisSlowlogLenTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.slowlog.RedisSlowlogResetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.slowlog.RedisSlowlogTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXackTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXaddTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXautoclaimTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXclaimTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXdelTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXlenTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXpendingTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXrangeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXreadTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXreadgroupTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXrevrangeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.RedisXtrimTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xgroup.RedisXgroupCreateTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xgroup.RedisXgroupCreateconsumerTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xgroup.RedisXgroupDelconsumerTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xgroup.RedisXgroupDestoryTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xgroup.RedisXgroupSetidTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xgroup.RedisXgroupTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xinfo.RedisXinfoConsumersTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xinfo.RedisXinfoGroupsTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xinfo.RedisXinfoStreamTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.stream.xinfo.RedisXinfoTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisAppendTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisDecrTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisDecrbyTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisGetsetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisIncrTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisIncrbyTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisIncrbyfloatTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisMgetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisMsetTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisMsetnxTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisPsetnexTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisSetexTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisSetnxTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisStrlenTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.string.RedisSubstrTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisBzmpopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisBzpopmaxTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisBzpopminTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZaddTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZcardTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZcountTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZdiffTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZdiffstoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZincrbyTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZinterTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZintercardTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZinterstoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZlexcountTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZmpopTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZmscoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZpopmaxTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZpopminTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrandmemberCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrangeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrangebylexTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrangebyscoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrangestoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrankTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZremCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZremrangebylexTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZremrangebyrankTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZremrangebyscoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrevrangeTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrevrangebylexTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrevrangebyscoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZrevrankTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZscanTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZscoreTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZunionTerminalCommandHandler;
import cn.oyzh.easyredis.terminal.zset.RedisZunionstoreTerminalCommandHandler;
import cn.oyzh.fx.terminal.standard.ClearTerminalCommandHandler;
import cn.oyzh.fx.terminal.standard.HelpTerminalCommandHandler;
import cn.oyzh.fx.terminal.util.TerminalManager2;

/**
 * @author oyzh
 * @since 2024-12-30
 */

public class RedisTerminalManager {

    /**
     * 注册处理器
     */
    public static void registerHandlers() {
        // 标准命令
        TerminalManager2.registerHandler(HelpTerminalCommandHandler.class);
        TerminalManager2.registerHandler(ClearTerminalCommandHandler.class);

        // acl命令
        TerminalManager2.registerHandler(RedisAclCatTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclDeluserTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclDryrunTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclGenpassTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclGetuserTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclListTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclLoadTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclLogTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclSaveTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclSetuserTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclUsersTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisAclWhoamiTerminalCommandHandler.class);

        // 基础命令
        TerminalManager2.registerHandler(RedisAuthTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisConnectTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisDelTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisDumpTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisEchoTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisExistsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFlushallTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFlushdbTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGetdelTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisHelloTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisKeysTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMigrateTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMoveTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPingTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisRandomkeyTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisRenamenxTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisRenameTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisRestoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSelectTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSwapdbTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisTypeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisUnlinkTerminalCommandHandler.class);

        // bit命令
        TerminalManager2.registerHandler(RedisBitcountTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBitfield_r0TerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBitfieldTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBitposTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBittopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGetbitTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSetbitTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSetrangeTerminalCommandHandler.class);

        // client命令
        TerminalManager2.registerHandler(RedisClientCachingTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientGetnameTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientGetredirTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientIdTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientInfoTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientKillTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientListTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientNoevictTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientNotouchTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientPuaseTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientReplyTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientSetinfoTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientSetnameTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientTrackinginfoTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientTrackingTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientUnblockTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClientUnpuaseTerminalCommandHandler.class);

        // cluster命令
        TerminalManager2.registerHandler(RedisClusterAddSlotsRangeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterAddSlotsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterBumpEpochTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterCountFailureReportsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterCountKeysInSlotTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterDelSlotsRangeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterDelSlotsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterFailoverTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterFlushSlotsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterForgetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterGetKeysInSlotTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterInfoTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterKeyslotTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterLinksTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterMeetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterMyidTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterMyShardIdTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterNodesTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterReplicateTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterResetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterSaveConfigTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterSetConfigEpochTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterSetSlotTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterShardsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterSlavesTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterSlotsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisClusterTerminalCommandHandler.class);

        // command命令
        TerminalManager2.registerHandler(RedisCommandCountTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisCommandDocsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisCommandGetkeysandflagsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisCommandGetkeysTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisCommandInfoTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisCommandListTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisCommandTerminalCommandHandler.class);

        // geo命令
        TerminalManager2.registerHandler(RedisGeoaddTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGeodistTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGeohashTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGeoposTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGeoradius_r0TerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGeoradiusbymember_r0TerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGeoradiusbymemberTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGeoradiusTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGeosearchstoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGeosearchTerminalCommandHandler.class);

        // hash命令
        TerminalManager2.registerHandler(RedisHdelCommandHandler.class);
        TerminalManager2.registerHandler(RedisHexistsCommandHandler.class);
        TerminalManager2.registerHandler(RedisHgetallCommandHandler.class);
        TerminalManager2.registerHandler(RedisHgetCommandHandler.class);
        TerminalManager2.registerHandler(RedisHincrbyfloatTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisHincrbyTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisHkeysCommandHandler.class);
        TerminalManager2.registerHandler(RedisHlenCommandHandler.class);
        TerminalManager2.registerHandler(RedisHmgetCommandHandler.class);
        TerminalManager2.registerHandler(RedisHrandfieldCommandHandler.class);
        TerminalManager2.registerHandler(RedisHscanTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisHsetCommandHandler.class);
        TerminalManager2.registerHandler(RedisHsetnxCommandHandler.class);
        TerminalManager2.registerHandler(RedisHstrlenCommandHandler.class);
        TerminalManager2.registerHandler(RedisHvalsCommandHandler.class);

        // hylog命令
        TerminalManager2.registerHandler(RedisPfaddTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPfcountTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPfmergeTerminalCommandHandler.class);

        // key命令
        TerminalManager2.registerHandler(RedisCopyTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisDbSizeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisExpireatTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisExpireTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisExpiretimeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGetexTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPersistTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPexpireatTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPexpireTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPexpiretimeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPttlTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisScanTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisTtlTerminalCommandHandler.class);

        // latency命令
        TerminalManager2.registerHandler(RedisLatencyDoctorTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLatencyGraphTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLatencyHistogramTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLatencyHistoryTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLatencyLatestTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLatencyResetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLatencyTerminalCommandHandler.class);

        // list命令
        TerminalManager2.registerHandler(RedisBlmoveTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBlmpopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBlpopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBrpoplpushTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBrpopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLindexTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLinsertTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLlenTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLmoveTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLmpopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLpopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLposTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLpushTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLpushxTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLrangeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLremTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLsetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLtrimTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisRpoplpushTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisRpopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisRpushTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisRpushxTerminalCommandHandler.class);

        // memory命令
        TerminalManager2.registerHandler(RedisMemoryDoctorTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMemoryMallocstatsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMemoryPurgeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMemoryStatsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMemoryTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMemoryUsageTerminalCommandHandler.class);

        // module命令
        TerminalManager2.registerHandler(RedisModuleListTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisModuleLoadexTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisModuleLoadTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisModuleTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisModuleUnloadTerminalCommandHandler.class);

        // other
        TerminalManager2.registerHandler(RedisAskingTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBgrewriteaofTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBgsaveTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFailoverTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLastsaveTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLolwutTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisObjectTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisReadonlyTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisReadwriteTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisReplicaofTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisResetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisRoleTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSaveTerminalCommandHandler.class);
        // TerminalManager2.registerHandler(RedisSentinelTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSlaveofTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisTimeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisTouchTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisWaitaofTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisWaitTerminalCommandHandler.class);

        // program-function
        TerminalManager2.registerHandler(RedisFunctionDeleteTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFunctionDumpTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFunctionFlushTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFunctionKillTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFunctionListTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFunctionLoadTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFunctionRestoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFunctionStatsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFunctionTerminalCommandHandler.class);

        // program-script
        TerminalManager2.registerHandler(RedisScriptDebugTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisScriptExistsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisScriptFlushTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisScriptKillTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisScriptLoadTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisScriptTerminalCommandHandler.class);

        // program
        TerminalManager2.registerHandler(RedisEval_r0TerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisEvalsha_r0TerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisEvalshaTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisEvalTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFcall_r0TerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisFcallTerminalCommandHandler.class);

        // pubsub
        TerminalManager2.registerHandler(RedisPsubscribeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPublishTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPubsubTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPunsubscribeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSpublishTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSsubscribeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSubscribeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSunsubscribeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisUnsubscribeTerminalCommandHandler.class);

        // server-config
        TerminalManager2.registerHandler(RedisConfigGetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisConfigResetStatTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisConfigRewriteTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisConfigSetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisConfigTerminalCommandHandler.class);

        // server
        TerminalManager2.registerHandler(RedisDiscardTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisExecTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisInfoTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisLcsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMonitorTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMuiltTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisShutdownTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSort_r0TerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSortTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisUnwatchTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisWatchTerminalCommandHandler.class);

        // set
        TerminalManager2.registerHandler(RedisSaddTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisScardTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSdiffstoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSdiffTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSintercarkTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSinterstoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSinterTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSismemberCommandHandler.class);
        TerminalManager2.registerHandler(RedisSmembersCommandHandler.class);
        TerminalManager2.registerHandler(RedisSmismemberCommandHandler.class);
        TerminalManager2.registerHandler(RedisSmoveTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSpopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSrandmemberCommandHandler.class);
        TerminalManager2.registerHandler(RedisSremCommandHandler.class);
        TerminalManager2.registerHandler(RedisSscanTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSunionstoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSunionTerminalCommandHandler.class);

        // slowlog命令
        TerminalManager2.registerHandler(RedisSlowlogGetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSlowlogLenTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSlowlogResetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSlowlogTerminalCommandHandler.class);

        // stream-xgroup
        TerminalManager2.registerHandler(RedisXgroupCreateconsumerTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXgroupCreateTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXgroupDelconsumerTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXgroupDestoryTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXgroupSetidTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXgroupTerminalCommandHandler.class);

        // stream-xinfo
        TerminalManager2.registerHandler(RedisXinfoConsumersTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXinfoGroupsTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXinfoStreamTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXinfoTerminalCommandHandler.class);

        // stream
        TerminalManager2.registerHandler(RedisXackTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXaddTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXautoclaimTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXclaimTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXdelTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXlenTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXpendingTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXrangeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXreadgroupTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXreadTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXrevrangeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisXtrimTerminalCommandHandler.class);

        // string
        TerminalManager2.registerHandler(RedisAppendTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisDecrbyTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisDecrTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisGetsetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisIncrbyfloatTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisIncrbyTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisIncrTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMgetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMsetnxTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisMsetTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisPsetnexTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSetexTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSetnxTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisStrlenTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisSubstrTerminalCommandHandler.class);

        // zset
        TerminalManager2.registerHandler(RedisBzmpopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBzpopmaxTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisBzpopminTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZaddTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZcardTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZcountTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZdiffstoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZdiffTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZincrbyTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZintercardTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZinterstoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZinterTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZlexcountTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZmpopTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZmscoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZpopmaxTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZpopminTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrandmemberCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrangebylexTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrangebyscoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrangestoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrangeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrankTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZremCommandHandler.class);
        TerminalManager2.registerHandler(RedisZremrangebylexTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZremrangebyrankTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZremrangebyscoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrevrangebylexTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrevrangebyscoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrevrangeTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZrevrankTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZscanTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZscoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZunionstoreTerminalCommandHandler.class);
        TerminalManager2.registerHandler(RedisZunionTerminalCommandHandler.class);
    }
}
